// <auto-generated />
using Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Demo.Migrations.UserProfile
{
    [DbContext(typeof(UserProfileContext))]
    [Migration("20180220204553_UserProf2")]
    partial class UserProf2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Demo.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserProfileID");

                    b.Property<string>("User_Name");

                    b.Property<string>("User_Password");

                    b.Property<bool>("User_SignIn_Status");

                    b.HasKey("ID");

                    b.HasIndex("UserProfileID");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("Demo.Models.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserModelID");

                    b.Property<string>("UserProfileStatusUpdate");

                    b.Property<string>("UserProfileSummary");

                    b.HasKey("ID");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Demo.Models.UserModel", b =>
                {
                    b.HasOne("Demo.Models.UserProfile")
                        .WithMany("UserFriends")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
